# Generated by Django 4.1.2 on 2023-02-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("user_name", models.CharField(blank=True, max_length=200)),
                ("user_email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
