# Generated by Django 2.0 on 2023-02-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('product_id', models.IntegerField(verbose_name='商品id')),
                ('content', models.CharField(max_length=2000, verbose_name='商品内容')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=200, verbose_name='商品名')),
                ('num', models.IntegerField(verbose_name='购买数量')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='价格')),
                ('address', models.CharField(max_length=2000, verbose_name='地址')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=200)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
