# Generated by Django 2.1.5 on 2023-03-16 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230311_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodities',
            options={'verbose_name_plural': 'commodities'},
        ),
    ]
