# Generated by Django 2.1.5 on 2023-03-18 14:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20230317_1801'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingCart',
            new_name='CartItem',
        ),
    ]
